### ISSUE TITLE
May 6th Prototype Issues

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#46]
For all of your complaints *cough I mean, comments about the prototype we will show you today, can you just add to the comments below so we can sort through them. We have a lot of small issues we are logging ourselves, so it will be good for us to best control duplicates and know exactly what version you were talking about.

thanks.

**Comment by DanRosauer** [comment]
It's looking great.  Heaps of functionality, great visually, and generally very easy to use.

Here are a few issues and ideas, in no particular order...
- looking at _Litoria eucnemis_.
  - the list of layers includes 2 WWF Ecoregion sets, but only 1 displays areas that I could see
  - the mouse turns from a hand to a pointer over the GBIF points, looking like you can click them, but doesn't do anything
  - the info links in both the results list and the layers list do nothing
  - deleting a layer from the layers list - first time I deleted the wrong one, because the visual difference for selected layers is quite subtle.
  - the ecoregion polygon looks great - of course no idea if its truer, but the shape follows the topography more and _looks_ more accurate ;-)
  - when I first added the MOL range map layer, I had the background set to satellite, and the semi transparent range didn't show up too well.  It looked great against the map background.  I know you have it set to launch as map by default.
- searching for Rattus, you get lots of results.  Could they be ordered by the taxon name so all the results for a species are together?
- looking at a wide-ranging species - _Rattus norvegicus_ the delay for tiling is noticeable, at each change of zoom level, so:
  - is it worth / practical showing some kind of 'it's doing something' display while it works.
  - is tiling on the fly going to get really slow when then are **lots** of users?
  - or are they still being cached so that lots of users = lots of layers ready tiled?
- the green downwards triangle which shows you've selected a layer in the results, looks like it might indicate a dropdown list.  Perhaps a different symbol could be better.
- what is the selection of GBIF records being shown?  It looks like very few, for well sampled species.  That might be the right choice, to avoid cramming the screen with 50,000 or more little dots, and perhaps download and performance issues.  But if it's a subset, that would ideally be obvious - perhaps even in the results where it says 'GBIF points'
- the uncertainty circles are great, but the really large ones are very distracting (looks like a 300km one for Macropus giganteus).
- just then, I zoomed in one step too far to see the full range of a species, and it seemed to slowly zoom back out - is that a feature?  If so, very cool.
- you can easily add in a layer which is not within the display extent, and then have to go looking for it.  How feasible would a **zoom to layer** option be for items on the layers list?

Dan

**Comment by andrewxhill** [comment]
Dan,

Great comments. I have answers for some of them, misdirection for others. Okay here goes.

``` text
looking at Litoria eucnemis.
the list of layers includes 2 WWF Ecoregion sets, but only 1 displays areas that I could see
```

Yes, I've noticed this in the past but never had a chance to get to the root of it. Thanks for the example, I found that the original CSVs in DropBox contain a lot of duplicates. I'm running a job right now to fix those.

``` text
the mouse turns from a hand to a pointer over the GBIF points, looking like you can click them, 
but doesn't do anything
```

You'll be able to click them soooon, but we just have no meaningful info included with them at this point.

``` text
the info links in both the results list and the layers list do nothing
```

Also, disabled for now, need to hash out metadata before we spend too much time filling those in.

``` text
deleting a layer from the layers list - first time I deleted the wrong one, because the visual difference 
for selected layers is quite subtle.
```

I'll keep this one in mind, I'm not sure an immediate fix. There are obvious options, but I need to spend a few minutes looking at the style sheets to figure out what will work. I do that in waves, next time i dig into them I'll try to come up with a solution.

``` text
the ecoregion polygon looks great - of course no idea if its truer, but the shape follows the topography 
more and looks more accurate ;-)
```

Yeah, totally. Thanks for the help with those.

``` text
when I first added the MOL range map layer, I had the background set to satellite, and the semi 
transparent range didn't show up too well. It looked great against the map background. I know 
you have it set to launch as map by default.
```

Also, we down the road we'll let users change their layer colors, so if something doesn't show up they can fix it.

``` text
searching for Rattus, you get lots of results. Could they be ordered by the taxon name so all the results for a 
species are together?
```

Did you try the filter to the left of the search results? I need to make sure the that 'Names' one is either sorted by popularity or alphabetically, but it works for doing what you ask already. Do a search for 'Rattus' and then click 'Rattus lugens' in the filter and you should only see two results.

``` text
looking at a wide-ranging species - Rattus norvegicus the delay for tiling is noticeable, at each change 
of zoom level, so:
is it worth / practical showing some kind of 'it's doing something' display while it works.
is tiling on the fly going to get really slow when then are lots of users?
or are they still being cached so that lots of users = lots of layers ready tiled?
```

Up until today I've had no caching turned on. a) I was not too concerned with it, and b) I had a mistake in the memcache key names, so no lookup of tiles would have worked. Tons of caching going on now. In fact, caching by zoom, so the more global the view the longer we keep the tile cached. So yeah, the more users there are the more caching that will happen, and really common tiles will have a good chance of still being in cache.

``` text
the green downwards triangle which shows you've selected a layer in the results, looks like it might 
indicate a dropdown list. Perhaps a different symbol could be better.
```

Yeah, I've hated that thing for a while. I did a new '+' sign, I want to tweek its darkness a bit, but otherwise I like it a lot better.

``` text
what is the selection of GBIF records being shown? It looks like very few, for well sampled species. 
That might be the right choice, to avoid cramming the screen with 50,000 or more little dots, and perhaps 
download and performance issues. But if it's a subset, that would ideally be obvious - perhaps even in 
the results where it says 'GBIF points'
```

Throttling GBIF results at the mo'. We just don't have any paging support yet in either our code or in consuming their API, so it will take a bit of dedicated time to crank it all the way. I agree though, there are some that are even less than our max, let me look a bit deeper.

``` text
the uncertainty circles are great, but the really large ones are very distracting (looks like a 
300km one for Macropus giganteus).
```

Agreeeed. I left them there, while trying to tone them down a bit. One thing that was happening, was PMs in the sameish spot with the sameish uncertainty were stacking up circles making them super dark. I added in a little method to try and prevent that. 

``` text
just then, I zoomed in one step too far to see the full range of a species, and it seemed to slowly 
zoom back out - is that a feature? If so, very cool.
```

Yes, that is Charlie, our magic code gnome making sure the zoom is right. No, I haven't seen that, maybe it is something from our old autozoom or maybe Aaron is working on something? We'll implement a 'zoom to bounds' button in the near future.

``` text
you can easily add in a layer which is not within the display extent, and then have to go looking 
for it. How feasible would a zoom to layer option be for items on the layers list?
```

Oop, yup, in the plans.

Thanks again Dan. Super helpful. 

a
