### ISSUE TITLE
search issue --- dipodomys

### ISSUE THREAD

**Issue by robgur** [andrewxhill/MOL#49]
The search for "dipodomys" (the kangaroo rat genus) returns no results.  Systematic of searches for a speciose higher level taxon?  (note, species names such as "dipodomys californicus" do appear).

**Comment by andrewxhill** [comment]
This was due to a fix i stubbed in yesterday. It had a problem i
didn't see at the time, fixed. dipodomys works fine.

On Mon, May 16, 2011 at 2:04 AM, robgur
reply@reply.github.com
wrote:

> The search for "dipodomys" (the kangaroo rat genus) returns no results.  Systematic of searches for a speciose higher level taxon?  (note, species names such as "dipodomys californicus" do appear).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrewxhill/MOL/issues/49

## 

Ecology and Evolutionary Biology
University of Colorado

http://biodiversity.colorado.edu
http://biodivertido.blogspot.com

**Comment by robgur** [comment]
OMG that was fast!  And!  Its 2:12am there, crazy man!
